services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    networks:
      - app_network
    environment:
      - 'PORT=5555'
      - 'LLM_URL=http://localhost:8000'
      - 'DB_URL=http://localhost:6333'
      - 'ENABLE_AUTH=true'
      - 'AUTH_PW_LENGTH=15'
      - 'AUTH_MAX_ATTEMPTS=5'
      - 'AUTH_LOCKOUT_DURATION=5'
      - 'AUTH_MODE=oidc'
      - 'OIDC_PROVIDER_URL=https://login.com/realms/identity'
      - 'OIDC_CLIENT_ID=hestia-dev'
      - 'OIDC_CLIENT_SECRET=some-secret'
      - 'AUTH_SECRET_KEY=some-key'
      - 'AUTH_TOKEN_LIFETIME=360'

  frontend:
    build:
      context: ./hestia-ui
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - 'PRIVATE_MICROSERVICE_URL=http://backend:5555'
      - 'PUBLIC_AUTH_MODE=oidc'
      - 'PORT=7860'


networks:
  app_network:
    driver: bridge