settings:
  digits: 3
  itemformat: yaml
  prefix: MRS-GDPR
  parent: MRS
  sep: '-'
attributes:
  defaults:
    importance: ''
    urgency: ''
    type: ''
    releasephase: ''
    requirement: ''
    verification: ''
    rationale: ''
    acceptancecriteria: ''
    comments: ''
    coverage: ''