from typing import Protocol, List, Dict, Any

class DBProvider(Protocol):
    def initialize(self, collection: str, config: Dict[str, Any]) -> None:
        ...
    def upsert(self, collection:str, points: List[Dict[str, Any]]) -> None:
        ...
    def query(self):
        ...
    def query_batch(self):
        ...
    def search(self, collection:str, *, dense: List[List[float]] | None = None, sparse=None, options=None):
        ...
