// Known inference parameters per LLM backend protocol, shown in the
// connection Settings modal. Each list is scoped to what that protocol's
// own API actually documents as a valid request-time parameter -- not
// everything a specific server implementation might additionally accept
// (e.g. vLLM's OpenAI-compatible server honors several non-standard extra
// fields, but those aren't guaranteed to exist on "OpenAI-compatible" in
// general, so they're deliberately left out here).

export type ParamType = 'number' | 'integer' | 'boolean' | 'text' | 'string-list' | 'object' | 'json';

export type ParamSpec = {
  key: string;
  label: string;
  type: ParamType;
  step?: number;
  // Populated for auto-generated OpenAI params; optional for hand-written ones.
  description?: string;
  // The provider's own documented default, shown as a hint -- leaving the
  // field blank still omits the key entirely (provider applies its default
  // itself); this is informational only, never used to pre-fill a value.
  default?: unknown;
  // Only present when type === 'object' -- flat nested sub-fields.
  fields?: ParamSpec[];
};

// Ollama's documented `options` fields for /api/generate and /api/chat.
// Defaults per https://docs.ollama.com/modelfile's "Valid Parameters and
// Values" table; mirostat/mirostat_tau/mirostat_eta defaults are no longer
// in that table (Ollama's docs have dropped Mirostat support from the
// current reference) but are well-established from the older Modelfile docs.
export const OLLAMA_GENERATION_PARAMS: ParamSpec[] = [
  { key: 'temperature', label: 'Temperature', type: 'number', step: 0.1, default: 0.8 },
  { key: 'top_p', label: 'Top P', type: 'number', step: 0.05, default: 0.9 },
  { key: 'top_k', label: 'Top K', type: 'integer', default: 40 },
  { key: 'min_p', label: 'Min P', type: 'number', step: 0.01, default: 0.0 },
  { key: 'num_predict', label: 'Max output tokens (num_predict)', type: 'integer', default: -1 },
  { key: 'num_ctx', label: 'Context window (num_ctx)', type: 'integer', default: 2048 },
  { key: 'repeat_penalty', label: 'Repeat penalty', type: 'number', step: 0.01, default: 1.0 },
  { key: 'repeat_last_n', label: 'Repeat last N', type: 'integer', default: 64 },
  { key: 'mirostat', label: 'Mirostat mode', type: 'integer', default: 0 },
  { key: 'mirostat_tau', label: 'Mirostat tau', type: 'number', step: 0.1, default: 5.0 },
  { key: 'mirostat_eta', label: 'Mirostat eta', type: 'number', step: 0.01, default: 0.1 },
  { key: 'seed', label: 'Seed', type: 'integer', default: 0 },
  { key: 'stop', label: 'Stop sequences', type: 'string-list' },
];

// Ollama's /api/embed shares the same generic `options` bag as /api/generate,
// but sampling-only knobs (temperature, mirostat, repeat_penalty, num_predict,
// ...) don't apply to an embedding call -- only context-window truncation
// does. Note: Ollama's /api/embed also has a top-level `truncate` request
// field, but that's not part of `options` and isn't plumbed through
// hestia/infrastructure/llm/ollama.py's embed() signature today, so it's
// left out here rather than silently doing nothing.
export const OLLAMA_EMBEDDING_PARAMS: ParamSpec[] = [
  { key: 'num_ctx', label: 'Context window (num_ctx)', type: 'integer', default: 2048 },
];

// The OpenAI Chat Completions API's own documented parameters -- true of
// any OpenAI-compatible endpoint, vLLM included.
//
// Regenerate this block with `npm run generate:openai-params` (see
// scripts/generate-openai-params.mjs), which pulls from openai/openai-openapi.
// Review the diff before committing -- the generator excludes deprecated
// fields and structural ones (messages/model/stream/store/moderation), and
// conservatively falls back to type: 'json' for anything with a non-flat
// or discriminated-union shape.
// AUTO-GENERATED:OPENAI_GENERATION_PARAMS START
export const OPENAI_GENERATION_PARAMS: ParamSpec[] = [
  { key: "audio", label: "Audio", type: "json", description: "Parameters for audio output. Required when audio output is requested with `modalities: [\"audio\"]`. [Learn more](/docs/guides/audio)." },
  { key: "frequency_penalty", label: "Frequency Penalty", type: "number", step: 0.01, default: 0, description: "Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim." },
  { key: "logit_bias", label: "Logit Bias", type: "json", description: "Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token." },
  { key: "logprobs", label: "Logprobs", type: "boolean", default: false, description: "Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`." },
  { key: "max_completion_tokens", label: "Max Completion Tokens", type: "integer", description: "An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and [reasoning tokens](/docs/guides/reasoning)." },
  { key: "metadata", label: "Metadata", type: "json", description: "Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters." },
  { key: "modalities", label: "Modalities", type: "string-list", description: "Output types that you would like the model to generate. Most models are capable of generating text, which is the default: `[\"text\"]` The `gpt-4o-audio-preview` model can also be used to [generate audio](/docs/guides/audio). To request that this model generate both text and audio responses, you can use: `[\"text\", \"audio\"]`" },
  { key: "n", label: "Number of completions (n)", type: "integer", default: 1, description: "How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs." },
  { key: "parallel_tool_calls", label: "Parallel Tool Calls", type: "boolean", default: true, description: "Whether to enable [parallel function calling](/docs/guides/function-calling#configuring-parallel-function-calling) during tool use." },
  { key: "prediction", label: "Prediction", type: "json", description: "Static predicted output content, such as the content of a text file that is being regenerated." },
  { key: "presence_penalty", label: "Presence Penalty", type: "number", step: 0.01, default: 0, description: "Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics." },
  { key: "prompt_cache_key", label: "Prompt Cache Key", type: "text", description: "Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](/docs/guides/prompt-caching)." },
  { key: "prompt_cache_options", label: "Prompt Cache Options", type: "object", description: "Options for prompt caching. Supported for `gpt-5.6` and later models. By default, OpenAI automatically chooses one implicit cache breakpoint. You can add explicit breakpoints to content blocks with `prompt_cache_breakpoint`. Each request can write up to four breakpoints. For cache matching, OpenAI considers up to the latest 80 breakpoints in the conversation, without a content-block lookback limit. Set `mode` to `explicit` to disable the implicit breakpoint. The `ttl` defaults to `30m`, which is currently the only supported value. See the [prompt caching guide](/docs/guides/prompt-caching) for current details.", fields: [{ key: "ttl", label: "Ttl", type: "text" }, { key: "mode", label: "Mode", type: "text" }] },
  { key: "reasoning_effort", label: "Reasoning Effort", type: "text", default: "medium", description: "Constrains effort on reasoning for reasoning models. Currently supported values are `none`, `minimal`, `low`, `medium`, `high`, `xhigh`, and `max`. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response. Not all reasoning models support every value. See the [reasoning guide](https://platform.openai.com/docs/guides/reasoning) for model-specific support." },
  { key: "response_format", label: "Response Format", type: "json", description: "An object specifying the format that the model must output. Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured Outputs which ensures the model will match your supplied JSON schema. Learn more in the [Structured Outputs guide](/docs/guides/structured-outputs). Setting to `{ \"type\": \"json_object\" }` enables the older JSON mode, which ensures the message the model generates is valid JSON. Using `json_schema` is preferred for models that support it." },
  { key: "safety_identifier", label: "Safety Identifier", type: "text", description: "A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies. The IDs should be a string that uniquely identifies each user, with a maximum length of 64 characters. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](/docs/guides/safety-best-practices#safety-identifiers)." },
  { key: "service_tier", label: "Service Tier", type: "text", default: "auto", description: "Specifies the processing type used for serving the request. - If set to 'auto', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use 'default'. - If set to 'default', then the request will be processed with the standard pricing and performance for the selected model. - If set to '[flex](/docs/guides/flex-processing)', then the request will be processed with the Flex Processing service tier. - To opt-in to [Fast mode](/api/docs/guides/fast-mode) at the request level, include the `service_tier=fast` or `service_tier=priority` parameter for Responses or Chat Completions. The response will show `service_tier=priority` regardless of if you specify `service_tier=fast` or `priority` in your request. - When not set, the default behavior is 'auto'. When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter." },
  { key: "stop", label: "Stop", type: "string-list", description: "Not supported with latest reasoning models `o3` and `o4-mini`. Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence." },
  { key: "stream_options", label: "Stream Options", type: "object", description: "Options for streaming response. Only set this when you set `stream: true`.", fields: [{ key: "include_usage", label: "Include Usage", type: "boolean", description: "If set, an additional chunk will be streamed before the `data: [DONE]` message. The `usage` field on this chunk shows the token usage statistics for the entire request, and the `choices` field will always be an empty array. All other chunks will also include a `usage` field, but with a null value. **NOTE:** If the stream is interrupted, you may not receive the final usage chunk which contains the total token usage for the request." }, { key: "include_obfuscation", label: "Include Obfuscation", type: "boolean", description: "When true, stream obfuscation will be enabled. Stream obfuscation adds random characters to an `obfuscation` field on streaming delta events to normalize payload sizes as a mitigation to certain side-channel attacks. These obfuscation fields are included by default, but add a small amount of overhead to the data stream. You can set `include_obfuscation` to false to optimize for bandwidth if you trust the network links between your application and the OpenAI API." }] },
  { key: "temperature", label: "Temperature", type: "number", step: 0.1, default: 1, description: "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both." },
  { key: "tool_choice", label: "Tool Choice", type: "json", description: "Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools. Specifying a particular tool via `{\"type\": \"function\", \"function\": {\"name\": \"my_function\"}}` forces the model to call that tool. `none` is the default when no tools are present. `auto` is the default if tools are present." },
  { key: "tools", label: "Tools", type: "json", description: "A list of tools the model may call. You can provide either [custom tools](/docs/guides/function-calling#custom-tools) or [function tools](/docs/guides/function-calling)." },
  { key: "top_logprobs", label: "Top logprobs", type: "integer", description: "An integer between 0 and 20 specifying the maximum number of most likely tokens to return at each token position, each with an associated log probability. In some cases, the number of returned tokens may be fewer than requested. `logprobs` must be set to `true` if this parameter is used." },
  { key: "top_p", label: "Top P", type: "number", step: 0.05, default: 1, description: "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or `temperature` but not both." },
  { key: "verbosity", label: "Verbosity", type: "text", default: "medium", description: "Constrains the verbosity of the model's response. Lower values will result in more concise responses, while higher values will result in more verbose responses. Currently supported values are `low`, `medium`, and `high`. The default is `medium`." },
  { key: "web_search_options", label: "Web Search Options", type: "json", description: "This tool searches the web for relevant results to use in a response. Learn more about the [web search tool](/docs/guides/tools-web-search?api-mode=chat)." },
];
// AUTO-GENERATED:OPENAI_GENERATION_PARAMS END

// The OpenAI Embeddings API's own documented parameters -- a completely
// different, disjoint shape from Chat Completions (no temperature/tools/etc.).
// Regenerate the same way as OPENAI_GENERATION_PARAMS above.
// AUTO-GENERATED:OPENAI_EMBEDDING_PARAMS START
export const OPENAI_EMBEDDING_PARAMS: ParamSpec[] = [
  { key: "dimensions", label: "Dimensions", type: "integer", description: "The number of dimensions the resulting output embeddings should have. Only supported in `text-embedding-3` and later models." },
  { key: "encoding_format", label: "Encoding Format", type: "text", default: "float", description: "The format to return the embeddings in. Can be either `float` or [`base64`](https://pypi.org/project/pybase64/)." },
  { key: "user", label: "User", type: "text", description: "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids)." },
];
// AUTO-GENERATED:OPENAI_EMBEDDING_PARAMS END

// Qdrant's retrieval-time search options (QdrantDB.search(), covering the
// full QdrantClient.query_points()/SearchParams surface) -- hand-curated,
// not auto-generated (Qdrant has no OpenAPI-spec generator like OpenAI's).
// For a hybrid (dense+sparse) query, hybrid_*/fusion/score_threshold/hnsw_ef/
// exact/indexed_only are all applied per-branch (on each Prefetch, pre-
// fusion) rather than to the fused result -- a raw threshold or HNSW knob
// doesn't have clean meaning against a post-fusion RRF/DBSF score.
// collection_name/query/using/prefetch/query_filter stay out of this list --
// they're inherent to a specific request, not a sensible per-connection
// default. quantization/acorn/shard_key_selector are exposed as raw JSON --
// niche, deeply-nested Qdrant features not worth a dedicated sub-form.
export const QDRANT_RETRIEVAL_PARAMS: ParamSpec[] = [
  { key: 'limit', label: 'Result limit (top_k)', type: 'integer', default: 50 },
  { key: 'score_threshold', label: 'Score threshold', type: 'number', step: 0.01, default: 0 },
  { key: 'with_payload', label: 'Include payload', type: 'boolean', default: true },
  { key: 'with_vectors', label: 'Include vectors', type: 'boolean', default: false },
  { key: 'offset', label: 'Pagination offset', type: 'integer' },
  { key: 'consistency', label: 'Read consistency', type: 'text' },
  { key: 'timeout', label: 'Query timeout (seconds)', type: 'integer' },
  { key: 'hnsw_ef', label: 'HNSW search depth (hnsw_ef)', type: 'integer' },
  { key: 'exact', label: 'Exact search (no approximation)', type: 'boolean', default: false },
  { key: 'indexed_only', label: 'Indexed segments only', type: 'boolean', default: false },
  { key: 'quantization', label: 'Quantization params', type: 'json' },
  { key: 'acorn', label: 'ACORN search params', type: 'json' },
  { key: 'shard_key_selector', label: 'Shard key selector', type: 'json' },
  { key: 'hybrid_sparse_limit', label: 'Hybrid: sparse prefetch limit', type: 'integer', default: 200 },
  { key: 'hybrid_dense_limit', label: 'Hybrid: dense prefetch limit', type: 'integer', default: 100 },
  { key: 'fusion', label: 'Hybrid: fusion method (rrf/dbsf)', type: 'text', default: 'rrf' },
];

const PARAM_SCHEMAS: Record<'ollama' | 'openai', Partial<Record<'generation' | 'embedding' | 'reranking', ParamSpec[]>>> = {
  ollama: {
    generation: OLLAMA_GENERATION_PARAMS,
    // No rerank HTTP call is implemented yet -- reuses the generation list
    // as a placeholder until reranking is actually wired up.
    reranking: OLLAMA_GENERATION_PARAMS,
    embedding: OLLAMA_EMBEDDING_PARAMS,
  },
  openai: {
    generation: OPENAI_GENERATION_PARAMS,
    reranking: OPENAI_GENERATION_PARAMS,
    embedding: OPENAI_EMBEDDING_PARAMS,
  },
};

export function getParamSpecs(
  backendType: 'ollama' | 'openai' | 'qdrant',
  purpose: 'generation' | 'embedding' | 'reranking' | 'vector_db',
): ParamSpec[] {
  if (backendType === 'qdrant') return purpose === 'vector_db' ? QDRANT_RETRIEVAL_PARAMS : [];
  return PARAM_SCHEMAS[backendType][purpose as 'generation' | 'embedding' | 'reranking'] ?? [];
}

export function paramValueToString(v: unknown): string {
  if (v == null) return '';
  if (Array.isArray(v)) return v.join(', ');
  return String(v);
}

export function parseParamValue(type: ParamType, raw: string): unknown {
  const trimmed = raw.trim();
  switch (type) {
    case 'boolean':
      return trimmed === 'true';
    case 'integer': {
      const n = parseInt(trimmed, 10);
      return Number.isNaN(n) ? undefined : n;
    }
    case 'number': {
      const n = Number(trimmed);
      return Number.isNaN(n) ? undefined : n;
    }
    case 'string-list':
      return trimmed
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);
    default:
      return raw;
  }
}

// Reconstructs a type: 'object' param's value from its flattened sub-field
// entries in a settingsParamValues-style map, keyed as `${spec.key}.${field.key}`.
// Returns undefined if none of the sub-fields were set.
export function buildObjectParam(spec: ParamSpec, values: Record<string, string>): Record<string, unknown> | undefined {
  const result: Record<string, unknown> = {};
  for (const field of spec.fields ?? []) {
    const raw = values[`${spec.key}.${field.key}`];
    if (!raw || raw.trim() === '') continue;
    const parsed = parseParamValue(field.type, raw);
    if (parsed === undefined) continue;
    if (Array.isArray(parsed) && parsed.length === 0) continue;
    result[field.key] = parsed;
  }
  return Object.keys(result).length === 0 ? undefined : result;
}

// Parses a type: 'json' param's raw textarea contents. Blank input is treated
// as "unset" rather than an error.
export function parseJsonParam(raw: string): { value?: unknown; error?: string } {
  const trimmed = raw.trim();
  if (trimmed === '') return {};
  try {
    return { value: JSON.parse(trimmed) };
  } catch {
    return { error: 'Invalid JSON' };
  }
}
