from typing import Any, Dict, List, Protocol


class DBProvider(Protocol):
    def initialize(self, collection: str, config: Dict[str, Any]) -> None: ...
    def upsert(self, collection: str, points: List[Dict[str, Any]]) -> None: ...
    def search(self, collection: str, *, dense: List[List[float]] | None = None, sparse=None, options=None): ...
    def delete_collection(self, collection: str) -> bool: ...
    @property
    def collections(self) -> dict: ...
    def get_collection(self, collection: str) -> dict | None: ...
    def delete_document(self, collection: str, source_uri: str) -> None: ...
